// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: app/micro/sudoku-solver.proto

package micro

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SudokuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sudoku []byte `protobuf:"bytes,1,opt,name=sudoku,proto3" json:"sudoku,omitempty"`
}

func (x *SudokuRequest) Reset() {
	*x = SudokuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_micro_sudoku_solver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SudokuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SudokuRequest) ProtoMessage() {}

func (x *SudokuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_micro_sudoku_solver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SudokuRequest.ProtoReflect.Descriptor instead.
func (*SudokuRequest) Descriptor() ([]byte, []int) {
	return file_app_micro_sudoku_solver_proto_rawDescGZIP(), []int{0}
}

func (x *SudokuRequest) GetSudoku() []byte {
	if x != nil {
		return x.Sudoku
	}
	return nil
}

type SudokuReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Sudoku []byte `protobuf:"bytes,2,opt,name=sudoku,proto3" json:"sudoku,omitempty"`
}

func (x *SudokuReply) Reset() {
	*x = SudokuReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_micro_sudoku_solver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SudokuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SudokuReply) ProtoMessage() {}

func (x *SudokuReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_micro_sudoku_solver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SudokuReply.ProtoReflect.Descriptor instead.
func (*SudokuReply) Descriptor() ([]byte, []int) {
	return file_app_micro_sudoku_solver_proto_rawDescGZIP(), []int{1}
}

func (x *SudokuReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SudokuReply) GetSudoku() []byte {
	if x != nil {
		return x.Sudoku
	}
	return nil
}

var File_app_micro_sudoku_solver_proto protoreflect.FileDescriptor

var file_app_micro_sudoku_solver_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x70, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2f, 0x73, 0x75, 0x64, 0x6f,
	0x6b, 0x75, 0x2d, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x73, 0x75, 0x64, 0x6f, 0x6b, 0x75, 0x5f, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x22, 0x27,
	0x0a, 0x0d, 0x53, 0x75, 0x64, 0x6f, 0x6b, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x75, 0x64, 0x6f, 0x6b, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x73, 0x75, 0x64, 0x6f, 0x6b, 0x75, 0x22, 0x3d, 0x0a, 0x0b, 0x53, 0x75, 0x64, 0x6f, 0x6b,
	0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x75, 0x64, 0x6f, 0x6b, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x73, 0x75, 0x64, 0x6f, 0x6b, 0x75, 0x32, 0x53, 0x0a, 0x06, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x72,
	0x12, 0x49, 0x0a, 0x0b, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x53, 0x75, 0x64, 0x6f, 0x6b, 0x75, 0x12,
	0x1c, 0x2e, 0x73, 0x75, 0x64, 0x6f, 0x6b, 0x75, 0x5f, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2e,
	0x53, 0x75, 0x64, 0x6f, 0x6b, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x73, 0x75, 0x64, 0x6f, 0x6b, 0x75, 0x5f, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x75,
	0x64, 0x6f, 0x6b, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x20, 0x5a, 0x1e, 0x53,
	0x75, 0x64, 0x6f, 0x6b, 0x75, 0x5f, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x2f, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_micro_sudoku_solver_proto_rawDescOnce sync.Once
	file_app_micro_sudoku_solver_proto_rawDescData = file_app_micro_sudoku_solver_proto_rawDesc
)

func file_app_micro_sudoku_solver_proto_rawDescGZIP() []byte {
	file_app_micro_sudoku_solver_proto_rawDescOnce.Do(func() {
		file_app_micro_sudoku_solver_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_micro_sudoku_solver_proto_rawDescData)
	})
	return file_app_micro_sudoku_solver_proto_rawDescData
}

var file_app_micro_sudoku_solver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_micro_sudoku_solver_proto_goTypes = []interface{}{
	(*SudokuRequest)(nil), // 0: sudoku_solver.SudokuRequest
	(*SudokuReply)(nil),   // 1: sudoku_solver.SudokuReply
}
var file_app_micro_sudoku_solver_proto_depIdxs = []int32{
	0, // 0: sudoku_solver.Solver.SolveSudoku:input_type -> sudoku_solver.SudokuRequest
	1, // 1: sudoku_solver.Solver.SolveSudoku:output_type -> sudoku_solver.SudokuReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_micro_sudoku_solver_proto_init() }
func file_app_micro_sudoku_solver_proto_init() {
	if File_app_micro_sudoku_solver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_micro_sudoku_solver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SudokuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_micro_sudoku_solver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SudokuReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_micro_sudoku_solver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_micro_sudoku_solver_proto_goTypes,
		DependencyIndexes: file_app_micro_sudoku_solver_proto_depIdxs,
		MessageInfos:      file_app_micro_sudoku_solver_proto_msgTypes,
	}.Build()
	File_app_micro_sudoku_solver_proto = out.File
	file_app_micro_sudoku_solver_proto_rawDesc = nil
	file_app_micro_sudoku_solver_proto_goTypes = nil
	file_app_micro_sudoku_solver_proto_depIdxs = nil
}
